version: "3"
services:
  api:
    # image: ghcr.io/fraunhoferportugal/trialmonitor-api:latest
    build:
      context: ./packages/server/
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=r3d1sc4ch3
      # - PUBLIC_URL=/trial-monitor
    restart: unless-stopped
    volumes:
      - ./config:/usr/config
      - ./data/logs/api/:/usr/src/app/logs/
    expose:
      - 80
    depends_on:
      - redis_cache
    labels:
      - traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)
      - traefik.http.routers.api.entrypoints=web

  frontend:
    # image: ghcr.io/fraunhoferportugal/trialmonitor-ui:latest
    build:
      context: ./packages/client/
      dockerfile: Dockerfile
      # args:
      #   - PUBLIC_URL=/trial-monitor
    restart: unless-stopped
    volumes:
      - ./config/ui-config.json:/usr/share/nginx/html/ui-config.json
    expose:
      - 80
    labels:
      - traefik.http.routers.frontend.rule=Host(`localhost`) && PathPrefix(`/`)
      - traefik.http.routers.frontend.entrypoints=web

  traefik:
    image: traefik:v2.9
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
      # - --log.level=DEBUG
      - --log.filePath=/logs/traefik.log
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/logs/traefik/:/logs/

  redis_cache:
    image: redis:alpine3.15
    command: redis-server --requirepass r3d1sc4ch3
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: unless-stopped
    volumes:
      - ./data/redis:/var/lib/redis
    expose:
      - 6379
