version: "3"
services:
  api:
    # image: ghcr.io/fraunhoferportugal/trialmonitor-api:latest
    build:
      context: ./packages/server/
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=r3d1sc4ch3
    restart: unless-stopped
    volumes:
      - ./config:/usr/config
      - ./deployment/wait-for-it.sh:/wait-for-it.sh
      - ./data/logs/api/:/usr/src/app/logs/
    command: /bin/sh -c 'chmod +x /wait-for-it.sh && /wait-for-it.sh -t 0 keycloak:8080 -- node -r source-map-support/register dist/index.js'
    expose:
      - 80
    depends_on:
      - keycloak
      - redis_cache
  frontend:
    # image: ghcr.io/fraunhoferportugal/trialmonitor-ui:latest
    build:
      context: ./packages/client/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./config/ui-config.json:/usr/share/nginx/html/ui-config.json
    expose:
      - 80
  nginx_proxy:
    image: nginx:1.21-alpine
    environment:
      - API_PORT=80
      - FRONTEND_PORT=80
    command: /bin/sh -c "envsubst '$${API_PORT} $${FRONTEND_PORT}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    restart: unless-stopped
    volumes:
      - ./deployment/nginx.auth.conf:/etc/nginx/conf.d/default.conf.template
      - ./data/logs/nginx/:/var/log/nginx/
    links:
      - api:api
      - frontend:frontend
      - keycloak:keycloak
    depends_on:
      - keycloak
      - api
      - frontend
    ports:
      - "80:80"
  keycloak-db:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=k3ycl04kUser
      - POSTGRES_DB=keycloak
    restart: unless-stopped
    volumes:
      - ./data/keycloak-postgres:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    restart: unless-stopped
    expose:
      - 8080
    depends_on:
      - keycloak-db
    links:
      - keycloak-db:keycloak-db
    entrypoint: /bin/sh -c 'chmod +x /wait-for-it.sh && /wait-for-it.sh -t 0 keycloak-db:5432 -- /opt/keycloak/bin/kc.sh start --auto-build --log=file,console'
    environment:
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=k3ycl04kUser
      - KC_PROXY=passthrough
      - KC_HOSTNAME_PATH=/auth
      - KC_HTTP_RELATIVE_PATH=/auth
    volumes:
      - ./deployment/wait-for-it.sh:/wait-for-it.sh
      - ./data/logs/keycloak/:/opt/keycloak/data/log/
  redis_cache:
    image: redis:alpine3.15
    command: redis-server --requirepass r3d1sc4ch3
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: unless-stopped
    volumes:
      - ./data/redis:/var/lib/redis
    expose:
      - 6379
