title: Trial Monitor
# usersDB: database_id

# cache:
#   expireTime: 3600

databases:
  - id: database_id
    type: sqlite
    config:
      dialect: sqlite
      storage: sample.sqlite
    users:
      table: users
      idField: userId
      fields: [ userId, name, age, gender ]
    timestampField: Date