title: Trial Monitor
usersDB: database_id

# cache:
#   expireTime: 3600

databases:
  - id: database_id
    type: sql
    config:
      dialect: sqlite
      storage: sample.sqlite
    users:
      table: users
      idField: Id
      fields: [ Name ]
      include:
        - table: userDetails
          fields: [Age, Gender]
          include:
            - table: clinicalConditions
              fields: [Description]
    timestampField: Date